

POST http://localhost:5000/users/create HTTP/1.1
Content-Type: application/json

{
    "email":"nos@email.com",
    "name":"nmddd",
    "age":40,
    "password":"123"
    # "outra": "erro"
}

###

PUT http://localhost:5000/users/update HTTP/1.1
Content-Type: application/json

{
    "email":"eu@email.com",
    "name":"nmddd",
    "age":40,
    "password":"123"
    # "outra": "erro"
}

###

DELETE http://localhost:5000/users/delete/czaax@email.com HTTP/1.1

###

 GET http://localhost:5000/users/find_all HTTP/1.1

###

GET http://localhost:5000/users/find_one/eu@email.com HTTP/1.1
