version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    networks:
      - my_net
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:

networks:
  my_net:
    driver: bridge
    name: my_net